// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package lock;

public interface ActivateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lock.ActivateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
