// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package lock;

public final class LockServiceImpl {
  private LockServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lock_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lock_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lock_PowerResponce_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lock_PowerResponce_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lock_ActivateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lock_ActivateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lock_ActivateResponce_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lock_ActivateResponce_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nlock.proto\022\004lock\"\036\n\014PowerRequest\022\016\n\006sw" +
      "itch\030\001 \001(\010\"\037\n\rPowerResponce\022\016\n\006switch\030\001 " +
      "\001(\010\"\037\n\017ActivateRequest\022\014\n\004text\030\001 \001(\t\" \n\020" +
      "ActivateResponce\022\014\n\004text\030\001 \001(\t2\214\001\n\013LockS" +
      "ervice\0228\n\013switchPower\022\022.lock.PowerReques" +
      "t\032\023.lock.PowerResponce\"\000\022C\n\014activateLock" +
      "\022\025.lock.ActivateRequest\032\026.lock.ActivateR" +
      "esponce\"\000(\0010\001B\031\n\004lockB\017LockServiceImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lock_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lock_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lock_PowerRequest_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_lock_PowerResponce_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lock_PowerResponce_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lock_PowerResponce_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_lock_ActivateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lock_ActivateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lock_ActivateRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_lock_ActivateResponce_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lock_ActivateResponce_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lock_ActivateResponce_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
