// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package lock;

public interface PowerResponceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lock.PowerResponce)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
