// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera.proto

package camera;

public interface CameraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:camera.CameraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 video = 1;</code>
   */
  int getVideo();
}
