// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera.proto

package camera;

public final class CameraServiceImpl {
  private CameraServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_camera_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_camera_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_camera_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_camera_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_camera_CameraRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_camera_CameraRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_camera_CameraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_camera_CameraResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014camera.proto\022\006camera\"\035\n\014PowerRequest\022\r" +
      "\n\005state\030\001 \001(\010\"\036\n\rPowerResponse\022\r\n\005video\030" +
      "\001 \001(\005\"\036\n\rCameraRequest\022\r\n\005video\030\001 \001(\005\"(\n" +
      "\016CameraResponse\022\026\n\016CameraResponse\030\001 \001(\t2" +
      "\224\001\n\rCameraService\022@\n\017cameraRecording\022\024.c" +
      "amera.PowerRequest\032\025.camera.PowerRespons" +
      "e\"\000\022A\n\014cameraChange\022\025.camera.CameraReque" +
      "st\032\026.camera.CameraResponse\"\0000\001B\035\n\006camera" +
      "B\021CameraServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_camera_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_camera_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_camera_PowerRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_camera_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_camera_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_camera_PowerResponse_descriptor,
        new java.lang.String[] { "Video", });
    internal_static_camera_CameraRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_camera_CameraRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_camera_CameraRequest_descriptor,
        new java.lang.String[] { "Video", });
    internal_static_camera_CameraResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_camera_CameraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_camera_CameraResponse_descriptor,
        new java.lang.String[] { "CameraResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
