// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera.proto

package camera;

public interface CameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:camera.CameraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string CameraResponse = 1;</code>
   */
  java.lang.String getCameraResponse();
  /**
   * <code>string CameraResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraResponseBytes();
}
