// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera.proto

package camera;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:camera.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 video = 1;</code>
   */
  int getVideo();
}
