// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera.proto

package camera;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:camera.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool state = 1;</code>
   */
  boolean getState();
}
