// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

public final class AlarmServiceImpl {
  private AlarmServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_SoundRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_SoundRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_SoundResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_SoundResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013alarm.proto\022\005alarm\"\036\n\014PowerRequest\022\016\n\006" +
      "switch\030\001 \001(\010\"\037\n\rPowerResponse\022\016\n\006switch\030" +
      "\001 \001(\010\"\035\n\014SoundRequest\022\r\n\005sound\030\001 \001(\005\"\036\n\r" +
      "SoundResponse\022\r\n\005sound\030\001 \001(\0052\206\001\n\014AlarmSe" +
      "rvice\022:\n\013switchAlarm\022\023.alarm.PowerReques" +
      "t\032\024.alarm.PowerResponse\"\000\022:\n\nsoundAlarm\022" +
      "\023.alarm.SoundRequest\032\023.alarm.SoundReques" +
      "t\"\0000\001B\033\n\005alarmB\020AlarmServiceImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alarm_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alarm_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_PowerRequest_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_alarm_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alarm_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_PowerResponse_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_alarm_SoundRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alarm_SoundRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_SoundRequest_descriptor,
        new java.lang.String[] { "Sound", });
    internal_static_alarm_SoundResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_alarm_SoundResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_SoundResponse_descriptor,
        new java.lang.String[] { "Sound", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
