// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alarm.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
