// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

public interface SoundRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alarm.SoundRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sound = 1;</code>
   */
  int getSound();
}
